[package]
name = "codegen"
version = "0.1.0"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf = "2.8.0"
# This pulls in protoc binary at buildtime, thus we use a sub-crate to not require that for module imports
protoc-rust = "2.8.0"
