[package]
name = "ics23"
version = "0.4.0"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
exclude = "codegen"
description = "Merkle proof verification library - implements Cosmos ICS23 Spec"
repository = "https://github.com/confio/ics23/tree/master/rust"
license = "Apache-2.0"

[workspace]
members = ["codegen"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
prost = "0.5"
bytes = "0.4.12"
hex = "0.3.2"
sha2 = "0.8"
sha3 = "0.8"
ripemd160 = "0.8"
failure = "0.1.5"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"